#!/bin/bash

set -e # exit on any error (non-zero exit code)

BOOKISH_DIR="/home/thegxnster/py/bookish"
cd "$BOOKISH_DIR"

if [ -f "$BOOKISH_DIR/.venv/bin/python3" ]; then
    PYTHON_BIN="$BOOKISH_DIR/.venv/bin/python3"
else
    PYTHON_BIN="python3"
fi

exec "$PYTHON_BIN" "$BOOKISH_DIR/src/bookish.py" "$@"
